### PR TITLE
Thomas.newauth

### PR DESCRIPTION
**Pull request by matrox471**
- added the new auth.
- remade the factory
- fixed the models
- changed the base model of the user model (illuminate's model)

### CODE REVIEW

**Review by matrox471 — COMMENTED** [review]
need to fix the nav bar

**Review by matrox471 — COMMENTED** [review]
should be ok now

**Comment by matrox471** [comment]
seeded user does not work

**Comment by matrox471** [comment]
cruds will need to be updated accordingly.

**Comment by matrox471** [comment]
normal user can access crud

**Review by matrox471 — COMMENTED** [review]
checked, generated user won't work but whatever

**Review by Fiyorden — APPROVED** [review]
Super les gars

**Pull request merged**
